Email templates
michalmikolajczyk/viking-garage-api pull request #15
Opened 2017-05-15 11:55 UTC by jonzee

2017-05-20 12:54 UTC, michalmikolajczyk requested changes
do sprawdzenia

2017-05-20 12:54 UTC, michalmikolajczyk commented on src/helpers/passport.ts
> +      { session: process.env.JWT_SESSION },
👍

2017-05-20 12:54 UTC, michalmikolajczyk commented on src/mailer/index.ts
> +      return res(`Email sent successfully ${info}`);
nice style

2017-05-20 12:54 UTC, michalmikolajczyk commented on src/mailer/index.ts
> +    transporter.sendMail(body, (err, info) => {
don't you need to return `transporter.sendMail()` here?

2017-05-20 12:54 UTC, michalmikolajczyk commented on src/mailer/templates.ts
> +Witaj w VIKING GARAGE!
to nie z tłumaczeń?

2017-05-21 15:04 UTC, michalmikolajczyk commented
please rebase on `master`

2017-05-22 10:12 UTC, jonzee commented on src/mailer/index.ts
> +    transporter.sendMail(body, (err, info) => {
nope, I passed callback to `sendMail`, it's not return any `Promise`, I resolved/rejected the `Promise` inside callback.

2017-05-22 10:15 UTC, jonzee commented on src/mailer/templates.ts
> +Witaj w VIKING GARAGE!
firstly I added module with translation, but for now we have only to emails so it's more convenient to translate them like this

2017-05-23 11:37 UTC, michalmikolajczyk approved these changes

2017-05-23 11:37 UTC, michalmikolajczyk commented
hey @jonzee can you try to rebase this on `master` please?

2017-05-24 12:24 UTC, michalmikolajczyk commented
halo

2017-05-24 22:04 UTC, merged