User edit
michalmikolajczyk/viking-garage-api pull request #16
Opened 2017-05-18 21:46 UTC by jonzee

2017-05-20 12:59 UTC, michalmikolajczyk requested changes
dobra robota, drobne poprawki i wrzuta

2017-05-20 12:59 UTC, michalmikolajczyk commented on src/services/user/get.ts
> +
why the empty line?

2017-05-20 12:59 UTC, michalmikolajczyk commented on src/tests/user/get.spec.ts
> +describe('user/get tests', () => {
please be precise in test naming

2017-05-20 12:59 UTC, michalmikolajczyk commented on src/tests/user/get.spec.ts
> +describe('user/get tests', () => {
```
describe('/user GET', () => {
...
```

2017-05-21 15:04 UTC, michalmikolajczyk commented
please rebase on `master`

2017-05-22 10:39 UTC, jonzee commented on src/services/user/get.ts
> +
it's separate required information from optional (and image)

2017-05-22 10:41 UTC, jonzee commented on src/tests/user/get.spec.ts
> +describe('user/get tests', () => {
it's describe path to file, not request method (likewise in frontend test)

2017-05-23 11:38 UTC, michalmikolajczyk approved these changes

2017-05-23 11:38 UTC, merged