Ride dialog
michalmikolajczyk/viking-garage-api pull request #23
Opened 2017-06-02 17:53 UTC by jonzee

2017-06-04 09:04 UTC, michalmikolajczyk requested changes
I think that `ride` and `booking` are kind of mixed here. I would prefer to use the work `booking` for the bookings (Ride reservations). Can we change that please?

2017-06-04 09:04 UTC, michalmikolajczyk commented on src/controllers/ride.ts
> +   * Create new ride booking
I don't really understand what is that `ride` entity. Is that a booking?

2017-06-04 09:04 UTC, michalmikolajczyk commented on src/controllers/ride.ts
> +   * @param {RideBody} object with booking info
if it is booking, let's name it `booking` throughout the apps, and not `ride`

2017-06-04 09:04 UTC, michalmikolajczyk commented on src/mailer/index.ts
> +const ride = process.env.VG_RIDE || 'viking.garage.app@gmail.com';
@jonzee that env variable name is enigmatic, let's change it to something clear like `VG_BOOKING_EMAIL` or sth

2017-06-04 09:04 UTC, michalmikolajczyk commented on src/services/ride/ride.ts
> +      .then(() => res.status(200).json({ msg: 'Booking ride successfully' }))
check grammar please

2017-06-11 20:31 UTC, michalmikolajczyk approved these changes

2017-06-11 20:31 UTC, michalmikolajczyk commented
@jonzee prośba o odniesienie się do komentarzy

2017-06-12 09:50 UTC, jonzee commented on src/controllers/ride.ts
> +   * Create new ride booking
It's more like contact form, I'll update this before merge

2017-06-12 13:25 UTC, merged